CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "CyberTests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsVisible" boolean NOT NULL,
    "Scope" integer NOT NULL,
    "TargetGroupId" integer,
    "TargetTeamId" integer,
    "Title" text NOT NULL,
    "ShortDescription" text NOT NULL,
    "FullDescription" text NOT NULL,
    "Difficulty" integer NOT NULL,
    "DurationInMinutes" integer NOT NULL,
    CONSTRAINT "PK_CyberTests" PRIMARY KEY ("Id")
);

CREATE TABLE "Instructions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(150) NOT NULL,
    "Description" text NOT NULL,
    "IconName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Instructions" PRIMARY KEY ("Id")
);

CREATE TABLE "Scenarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IsVisible" boolean NOT NULL,
    "Task" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Legend" text NOT NULL,
    "SchemaPath" text,
    "DurationInMinutes" integer NOT NULL,
    "DocumentationPath" text,
    "DocumentationFileName" text,
    "GameMode" integer NOT NULL,
    "Scope" integer NOT NULL,
    "TargetGroupId" integer,
    "TargetTeamId" integer,
    CONSTRAINT "PK_Scenarios" PRIMARY KEY ("Id")
);

CREATE TABLE "UserAnswerProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserScenarioProgressId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "IsCorrect" boolean NOT NULL,
    "FailedAttempts" integer NOT NULL,
    "LastSubmittedAnswer" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserAnswerProgresses" PRIMARY KEY ("Id")
);

CREATE TABLE "UserGroups" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_UserGroups" PRIMARY KEY ("Id")
);

CREATE TABLE "UserTestAnswers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserTestProgressId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "IsCorrect" boolean NOT NULL,
    CONSTRAINT "PK_UserTestAnswers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CyberTestId" integer NOT NULL,
    "Title" text NOT NULL,
    "FilePath" text NOT NULL,
    CONSTRAINT "PK_TestDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestDocuments_CyberTests_CyberTestId" FOREIGN KEY ("CyberTestId") REFERENCES "CyberTests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CyberTestId" integer NOT NULL,
    "Text" text NOT NULL,
    "Type" integer NOT NULL,
    "CorrectTextAnswer" text,
    CONSTRAINT "PK_TestQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestQuestions_CyberTests_CyberTestId" FOREIGN KEY ("CyberTestId") REFERENCES "CyberTests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTestProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "CyberTestId" integer NOT NULL,
    "Score" integer NOT NULL,
    "Status" integer NOT NULL,
    "StartedAt" timestamp with time zone,
    "TargetEndTime" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_UserTestProgresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserTestProgresses_CyberTests_CyberTestId" FOREIGN KEY ("CyberTestId") REFERENCES "CyberTests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InstructionAttachment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "InstructionId" integer NOT NULL,
    CONSTRAINT "PK_InstructionAttachment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InstructionAttachment_Instructions_InstructionId" FOREIGN KEY ("InstructionId") REFERENCES "Instructions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScenarioDocument" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "FilePath" text NOT NULL,
    "CyberScenarioId" integer NOT NULL,
    CONSTRAINT "PK_ScenarioDocument" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScenarioDocument_Scenarios_CyberScenarioId" FOREIGN KEY ("CyberScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScenarioQuestions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NOT NULL,
    "CorrectAnswer" text NOT NULL,
    "AwardPoints" integer NOT NULL,
    "PenaltyPoints" integer NOT NULL,
    "CyberScenarioId" integer NOT NULL,
    CONSTRAINT "PK_ScenarioQuestions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScenarioQuestions_Scenarios_CyberScenarioId" FOREIGN KEY ("CyberScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "TeamId" integer,
    "IsTeamAttempt" boolean NOT NULL,
    "CyberScenarioId" integer NOT NULL,
    "Score" integer NOT NULL,
    "Status" integer NOT NULL,
    "StartedAt" timestamp with time zone,
    "TargetEndTime" timestamp with time zone,
    "TimeSpent" interval,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_UserProgresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserProgresses_Scenarios_CyberScenarioId" FOREIGN KEY ("CyberScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "GroupId" integer,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_UserGroups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "UserGroups" ("Id") ON DELETE SET NULL
);

CREATE TABLE "UserTeams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "GroupId" integer NOT NULL,
    CONSTRAINT "PK_UserTeams" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserTeams_UserGroups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "UserGroups" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TestOptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TestQuestionId" integer NOT NULL,
    "Text" text NOT NULL,
    "IsCorrect" boolean NOT NULL,
    CONSTRAINT "PK_TestOptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TestOptions_TestQuestions_TestQuestionId" FOREIGN KEY ("TestQuestionId") REFERENCES "TestQuestions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTeamMappings" (
    "TeamsId" integer NOT NULL,
    "UsersId" text NOT NULL,
    CONSTRAINT "PK_UserTeamMappings" PRIMARY KEY ("TeamsId", "UsersId"),
    CONSTRAINT "FK_UserTeamMappings_AspNetUsers_UsersId" FOREIGN KEY ("UsersId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserTeamMappings_UserTeams_TeamsId" FOREIGN KEY ("TeamsId") REFERENCES "UserTeams" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_GroupId" ON "AspNetUsers" ("GroupId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_InstructionAttachment_InstructionId" ON "InstructionAttachment" ("InstructionId");

CREATE INDEX "IX_ScenarioDocument_CyberScenarioId" ON "ScenarioDocument" ("CyberScenarioId");

CREATE INDEX "IX_ScenarioQuestions_CyberScenarioId" ON "ScenarioQuestions" ("CyberScenarioId");

CREATE INDEX "IX_TestDocuments_CyberTestId" ON "TestDocuments" ("CyberTestId");

CREATE INDEX "IX_TestOptions_TestQuestionId" ON "TestOptions" ("TestQuestionId");

CREATE INDEX "IX_TestQuestions_CyberTestId" ON "TestQuestions" ("CyberTestId");

CREATE INDEX "IX_UserProgresses_CyberScenarioId" ON "UserProgresses" ("CyberScenarioId");

CREATE INDEX "IX_UserTeamMappings_UsersId" ON "UserTeamMappings" ("UsersId");

CREATE INDEX "IX_UserTeams_GroupId" ON "UserTeams" ("GroupId");

CREATE INDEX "IX_UserTestProgresses_CyberTestId" ON "UserTestProgresses" ("CyberTestId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260611070156_1', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE "UserTestAnswers" ADD "AnsweredAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "UserTestAnswers" ADD "SelectedAnswer" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260611112405_3', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "FirstName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetUsers" ADD "LastName" text NOT NULL DEFAULT '';

ALTER TABLE "AspNetUsers" ADD "MiddleName" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260611114545_user', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE "Instructions" ADD "Order" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260612093025_AddOrder', '10.0.7');

COMMIT;

