// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Routing;
using Microsoft.JSInterop;
using Radzen;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Threading;

namespace CyberPolygon.Components.Layout
{
    public partial class NavMenu : IDisposable
    {
        [Inject] private IDbContextFactory<ApplicationDbContext> ContextFactory { get; set; } = default!;

        private ApplicationUser? dbUser;
        private string? currentUrl;

        // Таймер для автоматического фонового обновления
        private Timer? _pollingTimer;

        private string UserDisplayFName => dbUser?.FirstName ?? "";
        private string UserDisplayLName => dbUser?.LastName ?? "";

        private string Nm => string.Join(" ", new[] { UserDisplayLName, UserDisplayFName }
            .Where(s => !string.IsNullOrWhiteSpace(s)))
            .Trim();

        private string UserDisplayName => string.IsNullOrWhiteSpace(Nm) ? "Гость" : Nm;

        private string DepartmentName => dbUser?.Group?.Name ?? "Не привязан";
        private string TeamName => dbUser?.Teams?.FirstOrDefault()?.Name ?? "Без команды";

        private int UserLevel = 1;
        private int UserXpPct = 0;
        private bool HasActiveScenario = false;
        private string ActiveScenarioTitle = "";

        protected override async Task OnInitializedAsync()
        {
            await LoadUserDataAsync();
        }

        protected override void OnInitialized()
        {
            currentUrl = NavigationManager.ToBaseRelativePath(NavigationManager.Uri);
            NavigationManager.LocationChanged += OnLocationChanged;

            // Настраиваем автообновление (каждые 30 секунд обновляет данные, если пользователь не меняет страницы)
            _pollingTimer = new Timer(OnTimerCallback, null, 30000, 30000);
        }

        private void OnTimerCallback(object? state)
        {
            _ = InvokeAsync(async () =>
            {
                await LoadUserDataAsync();
                StateHasChanged();
            });
        }

        private async void OnLocationChanged(object? sender, LocationChangedEventArgs e)
        {
            currentUrl = NavigationManager.ToBaseRelativePath(e.Location);

            // Принудительно обновляем данные в навбаре при каждом переходе по страницам
            await InvokeAsync(async () =>
            {
                await LoadUserDataAsync();
                StateHasChanged();
            });
        }

        private async Task LoadUserDataAsync()
        {
            var authState = await AuthProvider.GetAuthenticationStateAsync();
            var userId = authState.User.FindFirst(
                System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            if (userId != null)
            {
                try
                {
                    await using var context = await ContextFactory.CreateDbContextAsync();

                    dbUser = await context.Set<ApplicationUser>()
                        .Include(u => u.Group)
                        .Include(u => u.Teams)
                        .AsNoTracking()
                        .FirstOrDefaultAsync(u => EF.Property<string>(u, "Id") == userId);

                    if (dbUser != null)
                    {
                        var soloScore = await context.UserProgresses
                            .Where(p => p.UserId == userId && !p.IsTeamAttempt && p.Status == AttemptStatus.Completed)
                            .SumAsync(p => p.Score);

                        int teamScore = 0;
                        var myTeamId = dbUser.Teams.FirstOrDefault()?.Id;
                        if (myTeamId.HasValue)
                        {
                            teamScore = await context.UserProgresses
                                .Where(p => p.TeamId == myTeamId.Value && p.IsTeamAttempt && p.Status == AttemptStatus.Completed)
                                .SumAsync(p => p.Score);
                        }

                        int totalScore = soloScore + teamScore;

                        int prevXp = GetPrevRankXp(totalScore);
                        int nextXp = GetNextRankXp(totalScore);
                        UserLevel = GetLevel(totalScore);

                        int currentProgressScore = totalScore - prevXp;
                        int neededProgressScore = nextXp - prevXp;
                        UserXpPct = neededProgressScore > 0 ? (int)Math.Round((double)currentProgressScore / neededProgressScore * 100) : 100;

                        var activeSolo = await context.UserProgresses
                            .Include(p => p.Scenario)
                            .FirstOrDefaultAsync(p => p.UserId == userId && !p.IsTeamAttempt && p.Status == AttemptStatus.InProgress);

                        UserScenarioProgress? activeTeam = null;
                        if (myTeamId.HasValue)
                        {
                            activeTeam = await context.UserProgresses
                                .Include(p => p.Scenario)
                                .FirstOrDefaultAsync(p => p.TeamId == myTeamId.Value && p.IsTeamAttempt && p.Status == AttemptStatus.InProgress);
                        }

                        var activeScenario = activeSolo ?? activeTeam;
                        if (activeScenario != null && activeScenario.Scenario != null)
                        {
                            HasActiveScenario = true;
                            ActiveScenarioTitle = activeScenario.Scenario.Title ?? "Сценарий";
                        }
                        else
                        {
                            HasActiveScenario = false;
                            ActiveScenarioTitle = "";
                        }
                    }
                }
                catch
                {
                    dbUser = await UserManager.FindByIdAsync(userId);
                }
            }
        }

        private void GoToProfile()
        {
            NavigationManager.NavigateTo("profile");
        }

        private async Task HandleLogoutClick(MenuItemEventArgs args)
        {
            await JS.InvokeVoidAsync("eval", "document.getElementById('logoutForm').submit()");
        }

        void OnParentClicked(MenuItemEventArgs args) { }
        void OnChildClicked(MenuItemEventArgs args) { }

        // Вспомогательные методы вычисления уровня и опыта
        private int GetLevel(int xp)
        {
            if (xp < 250) return 1;
            if (xp < 1000) return 2;
            if (xp < 2500) return 3;
            if (xp < 5000) return 4;
            return 5;
        }

        private int GetPrevRankXp(int xp)
        {
            if (xp < 250) return 0;
            if (xp < 1000) return 250;
            if (xp < 2500) return 1000;
            if (xp < 5000) return 2500;
            return 5000;
        }

        private int GetNextRankXp(int xp)
        {
            if (xp < 250) return 250;
            if (xp < 1000) return 1000;
            if (xp < 2500) return 2500;
            if (xp < 5000) return 5000;
            return 10000;
        }

        public void Dispose()
        {
            NavigationManager.LocationChanged -= OnLocationChanged;
            _pollingTimer?.Dispose();
        }
    }
}