// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.AspNetCore.Components.Routing;
using Microsoft.JSInterop;
using Radzen;

namespace CyberPolygon.Components.Layout
{
    public partial class NavMenu
    {
        private ApplicationUser? user;
        private string? currentUrl;

        private string UserDisplayFName => user?.FirstName ?? "";
        private string UserDisplayLName => user?.LastName ?? "";

        private string Nm => string.Join(" ", new[] { UserDisplayLName, UserDisplayFName }
            .Where(s => !string.IsNullOrWhiteSpace(s)))
            .Trim();

        // Если оба пустые — показать "Гость"
        private string UserDisplayName => string.IsNullOrWhiteSpace(Nm) ? "Гость" : Nm;

        protected override async Task OnInitializedAsync()
        {
            var authState = await AuthProvider.GetAuthenticationStateAsync();
            var userId = authState.User.FindFirst(
                System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            if (userId != null)
            {
                user = await UserManager.FindByIdAsync(userId);
            }
        }

        protected override void OnInitialized()
        {
            currentUrl = NavigationManager.ToBaseRelativePath(NavigationManager.Uri);
            NavigationManager.LocationChanged += OnLocationChanged;
        }

        private void OnLocationChanged(object? sender, LocationChangedEventArgs e)
        {
            currentUrl = NavigationManager.ToBaseRelativePath(e.Location);
            StateHasChanged();
        }

        private async Task HandleLogoutClick(MenuItemEventArgs args)
        {
            await JS.InvokeVoidAsync("eval", "document.getElementById('logoutForm').submit()");
        }

        void OnParentClicked(MenuItemEventArgs args) { }
        void OnChildClicked(MenuItemEventArgs args) { }
    }
}
