// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.EntityFrameworkCore;
using Radzen;
using System.ComponentModel.DataAnnotations;

namespace CyberPolygon.Components.Pages
{
    public partial class Admin
    {
        private int activeTabIndex = 0;
        private bool isLoaded = false;
        private bool isProcessing = false; // Защита от двойных кликов при сохранении

        // Списки данных
        private List<UserGroup> groupsList = new();
        private List<UserTeam> teamsList = new();
        private List<ApplicationUser> usersList = new();
        private List<UserScenarioProgress> allScenarioProgressList = new();
        private List<UserTestProgress> allTestProgressList = new();

        private HashSet<string> adminUserIds = new();
        private HashSet<string> superAdminUserIds = new(); // Для отслеживания СуперАдминов
        private bool isCurrentUserSuperAdmin = false;

        // Переменные для модалок распределения
        private bool showGroupDistributionModal = false;
        private UserGroup? activeGroupContext;

        private bool showTeamDistributionModal = false;
        private UserTeam? activeTeamContext;

        // Переменные для модалок управления пользователями
        private bool showEditUserModal = false;
        private UserEditModel? editUserModel;

        private bool showCreateUserModal = false;

        private string newGroupName = "";
        private string newTeamName = "";
        private int selectedGroupIdForTeam;
        private UserCreationModel newUserModel = new();

        public class UserCreationModel
        {
            [Required(ErrorMessage = "Поле Логин обязательно")]
            //[EmailAddress(ErrorMessage = "Введите корректный Email адрес")]
            public string Login { get; set; } = string.Empty;

            [Required(ErrorMessage = "Придумайте пароль")]
            [MinLength(6, ErrorMessage = "Пароль должен содержать минимум 6 символов")]
            public string Password { get; set; } = string.Empty;

            [Required(ErrorMessage = "Укажите имя агента")]
            public string FirstName { get; set; } = string.Empty;

            [Required(ErrorMessage = "Укажите фамилию агента")]
            public string LastName { get; set; } = string.Empty;

            public string MiddleName { get; set; } = string.Empty;

            public bool IsAdmin { get; set; }

        }

        public class UserEditModel
        {
            public string Id { get; set; } = string.Empty;

            [Required(ErrorMessage = "Логин не может быть пустым")]
            //[EmailAddress(ErrorMessage = "Неверный формат Email")]
            public string Login { get; set; } = string.Empty;

            [Required(ErrorMessage = "Укажите имя агента")]
            public string FirstName { get; set; } = string.Empty;

            [Required(ErrorMessage = "Укажите фамилию агента")]
            public string LastName { get; set; } = string.Empty;

            public string MiddleName { get; set; } = string.Empty;

            public bool IsAdmin { get; set; }
        }

        private string GetUserDisplayName(ApplicationUser? u)
        {
            if (u == null) return "Неизвестный агент";
            var name = $"{u.LastName} {u.FirstName} {u.MiddleName}".Trim();
            return string.IsNullOrWhiteSpace(name) ? (u.UserName ?? "Агент") : name;
        }

        protected override async Task OnInitializedAsync()
        {
            await LoadAdminData();
            isLoaded = true;
        }

        private async Task LoadAdminData()
        {
            var authState = await AuthStateProvider.GetAuthenticationStateAsync();
            isCurrentUserSuperAdmin = authState.User.IsInRole("SuperAdmin");

            using var c = await ContextFactory.CreateDbContextAsync();
            groupsList = await c.UserGroups.ToListAsync();
            teamsList = await c.UserTeams.Include(t => t.Group).Include(t => t.Users).ToListAsync();
            usersList = await c.Set<ApplicationUser>().Include(u => u.Group).Include(u => u.Teams).ToListAsync();

            // Сортируем: сначала те, у кого запрошен Retake
            allScenarioProgressList = await c.UserProgresses.Include(p => p.Scenario)
                .OrderByDescending(p => p.IsRetakeRequested)
                .ThenByDescending(p => p.StartedAt)
                .ToListAsync();

            allTestProgressList = await c.Set<UserTestProgress>().Include(tp => tp.Test)
                .ThenInclude(t => t.Questions)
                .OrderByDescending(tp => tp.IsRetakeRequested)
                .ThenByDescending(tp => tp.StartedAt)
                .ToListAsync();

            // ОПТИМИЗАЦИЯ: Получаем всех админов и суперадминов одним запросом
            adminUserIds.Clear();
            superAdminUserIds.Clear();

            var adminRoleIds = await c.Roles
                .Where(r => r.Name == "Admin" || r.Name == "SuperAdmin")
                .Select(r => new { r.Id, r.Name })
                .ToListAsync();

            if (adminRoleIds.Any())
            {
                var roleIds = adminRoleIds.Select(r => r.Id).ToList();
                var userRoles = await c.UserRoles
                    .Where(ur => roleIds.Contains(ur.RoleId))
                    .ToListAsync();

                var superAdminRoleId = adminRoleIds.FirstOrDefault(r => r.Name == "SuperAdmin")?.Id;

                foreach (var ur in userRoles)
                {
                    adminUserIds.Add(ur.UserId);
                    if (superAdminRoleId != null && ur.RoleId == superAdminRoleId)
                    {
                        superAdminUserIds.Add(ur.UserId);
                    }
                }
            }

            // Поддерживаем актуальность открытых модалок при обновлении данных
            if (activeGroupContext != null)
            {
                activeGroupContext = groupsList.FirstOrDefault(g => g.Id == activeGroupContext.Id);
            }
            if (activeTeamContext != null)
            {
                activeTeamContext = teamsList.FirstOrDefault(t => t.Id == activeTeamContext.Id);
            }
        }

        // --- ЛОГИКА ДВУХКОЛОНОЧНЫХ МОДАЛОК РАСПРЕДЕЛЕНИЯ ---

        private void OpenGroupDistributionModal(UserGroup group)
        {
            activeGroupContext = group;
            showGroupDistributionModal = true;
        }

        private void CloseGroupDistributionModal()
        {
            showGroupDistributionModal = false;
            activeGroupContext = null;
        }

        private void OpenTeamDistributionModal(UserTeam team)
        {
            activeTeamContext = team;
            showTeamDistributionModal = true;
        }

        private void CloseTeamDistributionModal()
        {
            showTeamDistributionModal = false;
            activeTeamContext = null;
        }

        private async Task AssignUserToGroup(string uid, int? gid)
        {
            using var c = await ContextFactory.CreateDbContextAsync();
            var u = await c.Set<ApplicationUser>().Include(usr => usr.Teams).FirstOrDefaultAsync(usr => usr.Id == uid);
            if (u != null)
            {
                u.GroupId = gid;
                // Если убираем из группы, то выкидываем из всех команд этой группы
                if (gid == null)
                {
                    u.Teams.RemoveAll(t => true);
                }
                else
                {
                    // Если перевели в другую группу - чистим команды из старой
                    u.Teams.RemoveAll(t => t.GroupId != gid);
                }
                await c.SaveChangesAsync();
                await LoadAdminData();
            }
        }

        private async Task ToggleTeamMember(int tid, string uid, bool assign)
        {
            using var c = await ContextFactory.CreateDbContextAsync();
            var t = await c.UserTeams.Include(team => team.Users).FirstOrDefaultAsync(team => team.Id == tid);
            var u = await c.Users.FindAsync(uid);

            if (t != null && u != null)
            {
                if (assign)
                {
                    if (!t.Users.Any(x => x.Id == uid)) t.Users.Add(u);
                }
                else
                {
                    var target = t.Users.FirstOrDefault(x => x.Id == uid);
                    if (target != null) t.Users.Remove(target);
                }
                await c.SaveChangesAsync();
                await LoadAdminData();
            }
        }

        // --- МОДАЛКИ: СОЗДАНИЕ И РЕДАКТИРОВАНИЕ ПРОФИЛЯ ---

        private void OpenCreateUserModal()
        {
            newUserModel = new UserCreationModel();
            showCreateUserModal = true;
        }

        private void CloseCreateUserModal()
        {
            showCreateUserModal = false;
        }

        private void OpenEditUserModal(ApplicationUser u)
        {
            editUserModel = new UserEditModel
            {
                Id = u.Id,
                Login = u.UserName ?? "",
                FirstName = u.FirstName ?? "",
                LastName = u.LastName ?? "",
                MiddleName = u.MiddleName ?? "",
                IsAdmin = adminUserIds.Contains(u.Id) || superAdminUserIds.Contains(u.Id)
            };
            showEditUserModal = true;
        }

        private void CloseEditUserModal() { showEditUserModal = false; editUserModel = null; }

        // --- CRUD ПОДРАЗДЕЛЕНИЙ И КОМАНД ---
        private async Task CreateGroup()
        {
            if (string.IsNullOrWhiteSpace(newGroupName)) return;
            using var c = await ContextFactory.CreateDbContextAsync();
            c.UserGroups.Add(new UserGroup { Name = newGroupName });
            await c.SaveChangesAsync(); newGroupName = ""; await LoadAdminData();
        }

        private async Task DeleteGroup(int id)
        {
            var ok = await DialogService.Confirm("Удалить подразделение? Все агенты будут откреплены.", "Удаление", new ConfirmOptions { OkButtonText = "Удалить", CancelButtonText = "Отмена" });
            if (ok == true)
            {
                using var c = await ContextFactory.CreateDbContextAsync();
                var g = await c.UserGroups.FindAsync(id);
                if (g != null) { c.UserGroups.Remove(g); await c.SaveChangesAsync(); await LoadAdminData(); }
            }
        }

        private async Task CreateTeam()
        {
            if (string.IsNullOrWhiteSpace(newTeamName) || selectedGroupIdForTeam <= 0) return;
            using var c = await ContextFactory.CreateDbContextAsync();
            c.UserTeams.Add(new UserTeam { Name = newTeamName, GroupId = selectedGroupIdForTeam });
            await c.SaveChangesAsync();
            newTeamName = ""; await LoadAdminData();
        }

        private async Task DeleteTeam(int id)
        {
            var ok = await DialogService.Confirm("Удалить команду?", "Удаление", new ConfirmOptions { OkButtonText = "Удалить", CancelButtonText = "Отмена" });
            if (ok == true)
            {
                using var c = await ContextFactory.CreateDbContextAsync();
                var t = await c.UserTeams.FindAsync(id);
                if (t != null) { c.UserTeams.Remove(t); await c.SaveChangesAsync(); await LoadAdminData(); }
            }
        }

        // --- НОВЫЕ МЕТОДЫ ОДОБРЕНИЯ/ОТКЛОНЕНИЯ ПОВТОРОВ ---

        private async Task GrantScenarioRetake(int id)
        {
            await ScenarioService.GrantRetakeAsync(id);
            NotificationService.Notify(NotificationSeverity.Success, "Одобрено", "Доступ открыт.");
            await LoadAdminData();
        }

        private async Task RejectScenarioRetake(int id)
        {
            await ScenarioService.RejectRetakeAsync(id);
            NotificationService.Notify(NotificationSeverity.Info, "Отклонено", "Запрос отменен.");
            await LoadAdminData();
        }

        private async Task GrantTestRetake(int id)
        {
            await TestService.GrantRetakeAsync(id);
            NotificationService.Notify(NotificationSeverity.Success, "Одобрено", "Доступ открыт.");
            await LoadAdminData();
        }

        private async Task RejectTestRetake(int id)
        {
            await TestService.RejectRetakeAsync(id);
            NotificationService.Notify(NotificationSeverity.Info, "Отклонено", "Запрос отменен.");
            await LoadAdminData();
        }

        // --- CRUD ПОЛЬЗОВАТЕЛЕЙ ---
        private async Task CreateUser()
        {
            if (isProcessing) return;
            isProcessing = true;

            try
            {
                var (success, error) = await UserManagementService.CreateUserAsync(
                    newUserModel.Login, newUserModel.Password, newUserModel.FirstName, newUserModel.LastName, newUserModel.MiddleName, newUserModel.IsAdmin
                );

                if (success)
                {
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", $"Пользователь {newUserModel.Login} создан");
                    CloseCreateUserModal();
                    await LoadAdminData();
                }
                else
                {
                    NotificationService.Notify(NotificationSeverity.Error, "Ошибка создания", error);
                }
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Критическая ошибка", ex.Message);
            }
            finally
            {
                isProcessing = false;
            }
        }

        private async Task UpdateUser()
        {
            if (editUserModel == null || isProcessing) return;

            // Серверная защита от изменения СуперАдмина обычным Админом
            if (superAdminUserIds.Contains(editUserModel.Id) && !isCurrentUserSuperAdmin)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Отказ доступа", "Вы не можете редактировать профиль СуперАдминистратора.");
                CloseEditUserModal();
                return;
            }

            isProcessing = true;

            try
            {
                using var c = await ContextFactory.CreateDbContextAsync();
                var u = await c.Set<ApplicationUser>().FindAsync(editUserModel.Id);
                if (u != null)
                {
                    u.UserName = editUserModel.Login; u.FirstName = editUserModel.FirstName; u.LastName = editUserModel.LastName; u.MiddleName = editUserModel.MiddleName;
                    c.Update(u); await c.SaveChangesAsync();

                    bool currentlyAdmin = adminUserIds.Contains(u.Id) || superAdminUserIds.Contains(u.Id);
                    if (currentlyAdmin != editUserModel.IsAdmin) await UserManagementService.ToggleAdminRoleAsync(u.Id);

                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Данные пользователя сохранены");
                    CloseEditUserModal(); await LoadAdminData();
                }
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка БД", "Не удалось сохранить: " + ex.Message);
            }
            finally
            {
                isProcessing = false;
            }
        }

        private async Task DeleteUser(string userId)
        {
            // Серверная защита от удаления СуперАдмина
            if (superAdminUserIds.Contains(userId) && !isCurrentUserSuperAdmin)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Отказ доступа", "У вас нет прав для удаления СуперАдминистратора.");
                return;
            }

            var ok = await DialogService.Confirm("Удалить пользователя навсегда? Это действие необратимо.", "Удаление", new ConfirmOptions { OkButtonText = "Удалить", CancelButtonText = "Отмена" });
            if (ok == true)
            {
                var result = await UserManagementService.DeleteUserAsync(userId);
                if (result) { NotificationService.Notify(NotificationSeverity.Success, "Успех", "Пользователь удален"); await LoadAdminData(); }
                else { NotificationService.Notify(NotificationSeverity.Error, "Ошибка", "Не удалось удалить пользователя"); }
            }
        }

        private async Task ToggleAdminRole(string userId)
        {
            // Серверная защита: Обычный админ не может трогать роли СуперАдмина
            if (superAdminUserIds.Contains(userId) && !isCurrentUserSuperAdmin)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Отказ доступа", "Вы не можете изменить роль СуперАдминистратора.");
                return;
            }

            await UserManagementService.ToggleAdminRoleAsync(userId);
            await LoadAdminData();
            NotificationService.Notify(NotificationSeverity.Success, "Успех", "Права доступа изменены");
        }
    }
}