// <auto-generated/>
using CyberPolygon.Data.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Radzen;

namespace CyberPolygon.Components.Pages
{
    public partial class InstructionEditPage
    {
        [Parameter] public int? Id { get; set; }
        private InstructionModel Item { get; set; } = new();

        private List<IBrowserFile> uploadedFiles = new();
        private int maxAllowedFiles = 10;

        private readonly List<string> availableIcons = new()
    {
        "assignment", "terminal", "security", "shield", "bug_report",
        "lock", "visibility", "help_center", "description", "code", "lan"
    };

        // Вспомогательный метод для красивого русского перевода названий иконок
        private string GetIconDescription(string iconName) => iconName switch
        {
            "assignment" => "Документ / Задание",
            "terminal" => "Терминал / Консоль",
            "security" => "Безопасность / Щит",
            "shield" => "Защита",
            "bug_report" => "Уязвимость / Баг",
            "lock" => "Блокировка / Доступ",
            "visibility" => "Мониторинг / Обзор",
            "help_center" => "Справка / Помощь",
            "description" => "Описание / Файл",
            "code" => "Исходный код",
            "lan" => "Локальная сеть",
            _ => iconName
        };

        protected override async Task OnInitializedAsync()
        {
            if (Id.HasValue)
            {
                // Получаем список и находим нужную инструкцию
                var all = await InstructionService.GetAllAsync();
                Item = all.FirstOrDefault(i => i.Id == Id.Value) ?? new InstructionModel { IconName = "assignment" };
            }
            else
            {
                Item = new InstructionModel { IconName = "assignment" };
            }
        }

        private void LoadFiles(InputFileChangeEventArgs e)
        {
            foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
            {
                if (!uploadedFiles.Any(f => f.Name == file.Name))
                {
                    uploadedFiles.Add(file);
                }
            }
        }

        private void RemoveFile(IBrowserFile file)
        {
            uploadedFiles.Remove(file);
        }

        private async Task OnSave()
        {
            if (string.IsNullOrWhiteSpace(Item.Title) || string.IsNullOrWhiteSpace(Item.Description))
            {
                NotificationService.Notify(NotificationSeverity.Warning, "Ошибка", "Заполните название и содержание инструкции.");
                return;
            }

            try
            {
                if (Item.Id == 0)
                {
                    // Высчитываем порядок для новой инструкции
                    var all = await InstructionService.GetAllAsync();
                    Item.Order = all.Any() ? all.Max(i => i.Order) + 1 : 1;

                    await InstructionService.AddAsync(Item, uploadedFiles);
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Новая инструкция добавлена.");
                }
                else
                {
                    await InstructionService.UpdateAsync(Item);
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Инструкция обновлена.");
                }

                NavigationManager.NavigateTo("instruction");
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка сохранения", ex.Message);
            }
        }

        private void Cancel() => NavigationManager.NavigateTo("instruction");
    }
}
