// <auto-generated/>
using CyberPolygon.Data.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Radzen;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using System;

namespace CyberPolygon.Components.Pages
{
    public partial class InstructionEditPage
    {
        [Parameter] public int? Id { get; set; }
        private InstructionModel Item { get; set; } = new();

        private List<IBrowserFile> uploadedFiles = new();
        private int maxAllowedFiles = 10;

        // Лимит в 50 МБ для предотвращения тихих сбоев Blazor при выборе файла
        private long maxFileSize = 1024 * 1024 * 50;

        private readonly List<string> availableIcons = new()
        {
            "assignment", "terminal", "security", "shield", "bug_report",
            "lock", "visibility", "help_center", "description", "code", "lan",
            "dns", "hub", "gavel", "verified_user", "assessment", "radar", "query_stats"
        };

        private string GetIconDescription(string iconName) => iconName switch
        {
            "assignment" => "Документ / Задание",
            "terminal" => "Терминал / Консоль",
            "security" => "Безопасность / Щит",
            "shield" => "Защита",
            "bug_report" => "Уязвимость / Баг",
            "lock" => "Блокировка / Доступ",
            "visibility" => "Мониторинг / Обзор",
            "help_center" => "Справка / Помощь",
            "description" => "Описание / Файл",
            "code" => "Исходный код",
            "lan" => "Локальная сеть",
            "dns" => "Сервер / Инфраструктура",
            "hub" => "Координация / Узел",
            "gavel" => "Регламент / Закон",
            "verified_user" => "Аутентификация / Допуск",
            "assessment" => "Аналитика / График",
            "radar" => "Радар / Сканирование",
            "query_stats" => "Статистика / Поиск",
            _ => iconName
        };

        protected override async Task OnInitializedAsync()
        {
            if (Id.HasValue)
            {
                var all = await InstructionService.GetAllAsync();
                Item = all.FirstOrDefault(i => i.Id == Id.Value) ?? new InstructionModel { IconName = "assignment" };
            }
            else
            {
                Item = new InstructionModel { IconName = "assignment" };
            }
        }

        private async Task LoadFiles(InputFileChangeEventArgs e)
        {
            try
            {
                foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
                {
                    // Проверка размера файла перед добавлением
                    if (file.Size > maxFileSize)
                    {
                        NotificationService.Notify(NotificationSeverity.Warning, "Превышен размер", $"Файл {file.Name} больше 50 МБ и не будет загружен.");
                        continue;
                    }

                    if (!uploadedFiles.Any(f => f.Name == file.Name))
                    {
                        uploadedFiles.Add(file);
                    }
                }
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка добавления", "Файл слишком большой или произошла ошибка чтения.");
            }

            // Принудительно заставляем интерфейс перерисоваться, чтобы показать добавленные файлы
            StateHasChanged();
        }

        private void RemoveFile(IBrowserFile file)
        {
            uploadedFiles.Remove(file);
            StateHasChanged();
        }

        private async Task OnSave()
        {
            if (string.IsNullOrWhiteSpace(Item.Title) || string.IsNullOrWhiteSpace(Item.Description))
            {
                NotificationService.Notify(NotificationSeverity.Warning, "Система", "Заполните название и содержание блока.");
                return;
            }

            try
            {
                if (Item.Id == 0)
                {
                    var all = await InstructionService.GetAllAsync();
                    Item.Order = all.Any() ? all.Max(i => i.Order) + 1 : 1;

                    await InstructionService.AddAsync(Item, uploadedFiles);
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Новая инструкция добавлена в реестр.");
                }
                else
                {
                    /* Если ваш метод обновления в сервисе поддерживает файлы, 
                       замените следующую строку на: await InstructionService.UpdateAsync(Item, uploadedFiles); */
                    await InstructionService.UpdateAsync(Item);

                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Запись обновлена.");
                }

                NavigationManager.NavigateTo("instruction");
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка сохранения", ex.Message);
            }
        }

        private void Cancel() => NavigationManager.NavigateTo("instruction");
    }
}