// <auto-generated/>
using CyberPolygon.Data.Models;
using Radzen;

namespace CyberPolygon.Components.Pages
{
    public partial class Instruction
    {
        private List<InstructionModel> instructions = new();
        private bool isLoading = true;

        protected override async Task OnInitializedAsync()
        {
            await LoadData();
        }

        private async Task LoadData()
        {
            isLoading = true;
            try
            {
                instructions = await InstructionService.GetAllAsync();
                instructions = instructions.OrderBy(i => i.Order).ToList();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка загрузки", ex.Message);
            }
            finally
            {
                isLoading = false;
            }
        }

        // === ПЕРЕМЕЩЕНИЕ ===

        private async Task MoveInstruction(int currentIndex, int direction)
        {
            if (currentIndex + direction < 0 || currentIndex + direction >= instructions.Count) return;

            var currentItem = instructions[currentIndex];
            var swapItem = instructions[currentIndex + direction];

            // Меняем Order местами
            var tempOrder = currentItem.Order;
            currentItem.Order = swapItem.Order;
            swapItem.Order = tempOrder;

            try
            {
                await InstructionService.UpdateOrderAsync(currentItem);
                await InstructionService.UpdateOrderAsync(swapItem);

                NotificationService.Notify(NotificationSeverity.Success, "Система", "Порядок инструкций обновлён.");
                await LoadData();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка", ex.Message);
            }
        }

        // === УДАЛЕНИЕ ===

        private async Task DeleteInstruction(int id)
        {
            try
            {
                await InstructionService.DeleteAsync(id);
                NotificationService.Notify(NotificationSeverity.Warning, "Терминал", "Инструкция удалена.");
                await LoadData();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка удаления", ex.Message);
            }
        }
    }
}
