// <auto-generated/>
using CyberPolygon.Data.Models;
using Radzen;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using System;

namespace CyberPolygon.Components.Pages
{
    public partial class Instruction
    {
        private List<InstructionModel> instructions = new();
        private bool isLoading = true;

        // Поле для хранения выбранной для полноэкранного просмотра инструкции
        private InstructionModel? selectedInstruction;

        // Поле для хранения ID инструкции, которую собираемся удалить
        private int? itemToDeleteId;

        protected override async Task OnInitializedAsync()
        {
            try
            {
                await LoadData();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка инициализации", ex.Message);
            }
        }

        private async Task LoadData()
        {
            isLoading = true;
            try
            {
                instructions = await InstructionService.GetAllAsync();
                instructions = instructions.OrderBy(i => i.Order).ToList();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка загрузки", ex.Message);
            }
            finally
            {
                isLoading = false;
            }
        }

        // === МОДАЛЬНОЕ ОКНО ЧТЕНИЯ ===

        private void OpenInstruction(InstructionModel item)
        {
            selectedInstruction = item;
        }

        private void CloseInstruction()
        {
            selectedInstruction = null;
        }

        // === ПЕРЕМЕЩЕНИЕ ===

        private async Task MoveInstruction(int currentIndex, int direction)
        {
            if (currentIndex + direction < 0 || currentIndex + direction >= instructions.Count) return;

            var currentItem = instructions[currentIndex];
            var swapItem = instructions[currentIndex + direction];

            // Меняем Order местами
            var tempOrder = currentItem.Order;
            currentItem.Order = swapItem.Order;
            swapItem.Order = tempOrder;

            try
            {
                await InstructionService.UpdateOrderAsync(currentItem);
                await InstructionService.UpdateOrderAsync(swapItem);

                NotificationService.Notify(NotificationSeverity.Success, "Система", "Порядок инструкций обновлён.");
                await LoadData();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка", ex.Message);
            }
        }

        // === МОДАЛЬНОЕ ОКНО УДАЛЕНИЯ ===

        private void ShowDeleteConfirmation(int id)
        {
            itemToDeleteId = id;
        }

        private void HideDeleteConfirmation()
        {
            itemToDeleteId = null;
        }

        private async Task ExecuteDelete()
        {
            if (!itemToDeleteId.HasValue) return;

            try
            {
                await InstructionService.DeleteAsync(itemToDeleteId.Value);
                NotificationService.Notify(NotificationSeverity.Warning, "Терминал", "Блок инструкций удален.");

                // Скрываем окно подтверждения
                itemToDeleteId = null;

                await LoadData();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка удаления", ex.Message);
            }
        }
    }
}