// <auto-generated/>
using CyberPolygon.Data.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Radzen;
using System.Security.Claims;

namespace CyberPolygon.Components.Pages
{
    public partial class InstructionEditPage
    {
        [Inject] private AuthenticationStateProvider AuthStateProvider { get; set; } = default!;

        [Parameter] public int? Id { get; set; }
        private InstructionModel Item { get; set; } = new();

        private int maxAllowedFiles = 10;
        private long maxFileSize = 1024 * 1024 * 50; // 50 MB

        private readonly List<string> availableIcons = new()
        {
            "assignment", "terminal", "security", "shield", "bug_report",
            "lock", "visibility", "help_center", "description", "code", "lan",
            "dns", "hub", "gavel", "verified_user", "assessment", "radar", "query_stats"
        };

        private string GetIconDescription(string iconName) => iconName switch
        {
            "assignment" => "Документ / Задание",
            "terminal" => "Терминал / Консоль",
            "security" => "Безопасность / Щит",
            "shield" => "Защита",
            "bug_report" => "Уязвимость / Баг",
            "lock" => "Блокировка / Доступ",
            "visibility" => "Мониторинг / Обзор",
            "help_center" => "Справка / Помощь",
            "description" => "Описание / Файл",
            "code" => "Исходный код",
            "lan" => "Локальная сеть",
            "dns" => "Сервер / Инфраструктура",
            "hub" => "Координация / Узел",
            "gavel" => "Регламент / Закон",
            "verified_user" => "Аутентификация / Допуск",
            "assessment" => "Аналитика / График",
            "radar" => "Радар / Сканирование",
            "query_stats" => "Статистика / Поиск",
            _ => iconName
        };

        protected override async Task OnInitializedAsync()
        {
            if (Id.HasValue)
            {
                var all = await InstructionService.GetAllAsync();
                Item = all.FirstOrDefault(i => i.Id == Id.Value) ?? new InstructionModel { IconName = "assignment" };
            }
            else
            {
                Item = new InstructionModel { IconName = "assignment", Attachments = new() };
            }
        }

        private async Task LoadFiles(InputFileChangeEventArgs e)
        {
            try
            {
                foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
                {
                    if (file.Size > maxFileSize)
                    {
                        NotificationService.Notify(NotificationSeverity.Warning, "Превышен размер", $"Файл {file.Name} больше 50 МБ.");
                        continue;
                    }

                    // Безопасное чтение без MemoryStream и CopyToAsync
                    var buffer = new byte[file.Size];
                    await using var stream = file.OpenReadStream(maxAllowedSize: maxFileSize);

                    int totalRead = 0;
                    while (totalRead < file.Size)
                    {
                        int read = await stream.ReadAsync(buffer, totalRead, (int)file.Size - totalRead);
                        if (read == 0) break;
                        totalRead += read;
                    }

                    var attachment = new InstructionAttachment
                    {
                        FileName = file.Name,
                        ContentType = string.IsNullOrWhiteSpace(file.ContentType) ? "application/octet-stream" : file.ContentType,
                        Content = buffer
                    };

                    Item.Attachments.Add(attachment);
                }
                NotificationService.Notify(NotificationSeverity.Success, "Успех", "Файлы добавлены в блок");
            }
            catch (TaskCanceledException)
            {
                NotificationService.Notify(NotificationSeverity.Warning, "Внимание", "Чтение прервано браузером. Попробуйте еще раз.");
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка загрузки", ex.Message);
            }
            StateHasChanged();
        }

        private void RemoveFile(InstructionAttachment file)
        {
            Item.Attachments.Remove(file);
            StateHasChanged();
        }

        private async Task OnSave()
        {
            if (string.IsNullOrWhiteSpace(Item.Title) || string.IsNullOrWhiteSpace(Item.Description))
            {
                NotificationService.Notify(NotificationSeverity.Warning, "Внимание", "Заполните название и содержание блока.");
                return;
            }

            try
            {
                if (Item.Id == 0)
                {
                    var authState = await AuthStateProvider.GetAuthenticationStateAsync();
                    Item.AuthorId = authState.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                    await InstructionService.AddAsync(Item);
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Инструкция добавлена.");
                }
                else
                {
                    await InstructionService.UpdateAsync(Item);
                    NotificationService.Notify(NotificationSeverity.Success, "Успех", "Инструкция обновлена.");
                }

                NavigationManager.NavigateTo("instruction");
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка сохранения", ex.Message);
            }
        }

        private void Cancel() => NavigationManager.NavigateTo("instruction");
    }
}