// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using static CyberPolygon.Data.ApplicationDbContext;

namespace CyberPolygon.Components.Pages
{
    public partial class Profile
    {
        private int activeTabIndex = 0; private bool isLoaded = false;
        private ApplicationUser? user;
        private UserScenarioProgress? activeScenario = null; private int activeScenarioQuestionsSolved = 0; private int activeScenarioTotalQuestions = 0;

        // Статистика
        private int totalScenarios = 0; private int soloScenarios = 0; private int teamScenarios = 0;
        private int completedScenariosCount = 0; private int totalAttemptsScenarios = 0; private int totalScenarioScore = 0; private string scenarioSuccessRate = "0";
        private List<UserScenarioProgress> allScenarioAttempts = new();

        private int totalTests = 0; private int completedTestsCount = 0; private int totalAttemptsTests = 0;
        private string testSuccessRate = "0";
        private string correctAnswersPercent = "0"; private int totalCorrectAnswers = 0; private int totalQuestionsAnswered = 0;
        private List<TestAttemptDto> allTestAttempts = new();

        private List<TeamMemberDto> myTeamMembers = new();

        // Лидерборды
        private List<string> leaderboardCategories = new() { "Сценарии", "Тесты" }; private string selectedCategory = "Сценарии";
        private List<string> leaderboardFilters = new() { "Все подразделения", "Мое подразделение" }; private string selectedFilter = "Все подразделения";
        private List<UserLeaderboardDto> topUsers = new(); private List<TeamLeaderboardDto> topTeams = new();
        private List<TestUserLeaderboardDto> topTestUsers = new(); private TestLeaderboardStats testLeaderboardStats = new();

        private string UserDisplayFullName
        {
            get
            {
                var name = $"{user?.LastName} {user?.FirstName}".Trim();
                return string.IsNullOrWhiteSpace(name) ? (user?.UserName ?? "Оперативник") : name;
            }
        }

        private string GetUserDisplayName(ApplicationUser? u)
        {
            if (u == null) return "Пользователь";
            var name = $"{u.LastName} {u.FirstName} {u.MiddleName}".Trim();
            return string.IsNullOrWhiteSpace(name) ? (u.UserName ?? "Пользователь") : name;
        }

        // ЛОГИКА РАНГОВ
        private string GetRankName(int xp)
        {
            if (xp < 250) return "Стажер";
            if (xp < 1000) return "Специалист";
            if (xp < 2500) return "Старший специалист";
            if (xp < 5000) return "Ведущий инженер";
            return "Элитный хакер";
        }

        private int GetPrevRankXp(int xp)
        {
            if (xp < 250) return 0;
            if (xp < 1000) return 250;
            if (xp < 2500) return 1000;
            if (xp < 5000) return 2500;
            return 5000;
        }

        private int GetNextRankXp(int xp)
        {
            if (xp < 250) return 250;
            if (xp < 1000) return 1000;
            if (xp < 2500) return 2500;
            if (xp < 5000) return 5000;
            return 10000;
        }

        // ХОЛСТ КАРТЫ АКТИВНОСТИ
        private int GetActivityLevelForDate(DateTime date)
        {
            int count = allScenarioAttempts.Count(p => p.StartedAt.HasValue && p.StartedAt.Value.Date == date.Date);
            if (count == 0) return 0;
            if (count == 1) return 1;
            if (count == 2) return 2;
            if (count == 3) return 3;
            return 4;
        }

        private string GetDifficultyColor(string d) => d switch { "Easy" => "var(--success-color)", "Medium" => "var(--warning-color)", "Hard" => "var(--danger-color)", _ => "var(--text-muted)" };

        private void GoToActiveTerminal()
        {
            if (activeScenario != null)
            {
                NavigationManager.NavigateTo($"/scenario/{activeScenario.CyberScenarioId}/workspace");
            }
        }

        protected override async Task OnInitializedAsync()
        {
            await LoadBaseData();
            await UpdateLeaderboards();
            isLoaded = true;
        }

        private async Task LoadBaseData()
        {
            var s = await AuthProvider.GetAuthenticationStateAsync();
            var uid = s.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            using var c = await ContextFactory.CreateDbContextAsync();
            if (!string.IsNullOrEmpty(uid))
            {
                user = await c.Set<ApplicationUser>().Include(u => u.Group).Include(u => u.Teams).FirstOrDefaultAsync(u => u.Id == uid);

                UserScenarioProgress? activeSolo = await c.UserProgresses.Include(p => p.Scenario).ThenInclude(sc => sc.Questions).FirstOrDefaultAsync(p => p.UserId == uid && !p.IsTeamAttempt && p.Status == AttemptStatus.InProgress);
                UserScenarioProgress? activeTeam = null;

                int? myTeamId = user?.Teams.FirstOrDefault()?.Id;
                if (myTeamId.HasValue)
                {
                    activeTeam = await c.UserProgresses.Include(p => p.Scenario).ThenInclude(sc => sc.Questions).FirstOrDefaultAsync(p => p.TeamId == myTeamId.Value && p.IsTeamAttempt && p.Status == AttemptStatus.InProgress);
                }

                activeScenario = activeSolo ?? activeTeam;
                if (activeScenario != null)
                {
                    activeScenarioTotalQuestions = activeScenario.Scenario.Questions.Count;
                    activeScenarioQuestionsSolved = await c.Set<UserAnswerProgress>().CountAsync(a => a.UserScenarioProgressId == activeScenario.Id);
                }

                var av = await c.Scenarios.Where(sc => sc.IsVisible).ToListAsync();
                totalScenarios = av.Count; soloScenarios = av.Count(sc => sc.Scope == VisibilityScope.Public || sc.Scope == VisibilityScope.GroupOnly);
                teamScenarios = av.Count(sc => sc.Scope == VisibilityScope.TeamOnly);

                var soloAttempts = await c.UserProgresses.Include(p => p.Scenario).Where(p => p.UserId == uid && !p.IsTeamAttempt).ToListAsync();
                var teamAttempts = new List<UserScenarioProgress>();

                if (myTeamId.HasValue)
                {
                    teamAttempts = await c.UserProgresses.Include(p => p.Scenario).Where(p => p.TeamId == myTeamId.Value && p.IsTeamAttempt).ToListAsync();
                }

                allScenarioAttempts = soloAttempts.Concat(teamAttempts).OrderByDescending(p => p.StartedAt).ToList();
                completedScenariosCount = allScenarioAttempts.Count(p => p.Status == AttemptStatus.Completed);
                totalScenarioScore = allScenarioAttempts.Where(p => p.Status == AttemptStatus.Completed).Sum(sc => sc.Score);
                totalAttemptsScenarios = allScenarioAttempts.Count;
                scenarioSuccessRate = totalAttemptsScenarios > 0 ? ((int)Math.Round((double)completedScenariosCount / totalAttemptsScenarios * 100)).ToString() : "0";

                var at = await c.Set<CyberTest>().Where(t => t.IsVisible).ToListAsync();
                totalTests = at.Count;
                var tps = await c.Set<UserTestProgress>().Include(tp => tp.Test).ThenInclude(t => t.Questions).Where(tp => tp.UserId == uid).OrderByDescending(tp => tp.CompletedAt).ToListAsync();
                totalAttemptsTests = tps.Count; completedTestsCount = tps.Count(tp => tp.Status == AttemptStatus.Completed);
                testSuccessRate = totalAttemptsTests > 0 ? ((int)Math.Round((double)completedTestsCount / totalAttemptsTests * 100)).ToString() : "0";
                totalCorrectAnswers = tps.Where(tp => tp.Status == AttemptStatus.Completed).Sum(tp => tp.Score);
                totalQuestionsAnswered = tps.Where(tp => tp.Status == AttemptStatus.Completed).Sum(tp => tp.Test?.Questions?.Count ?? 0);
                correctAnswersPercent = totalQuestionsAnswered > 0 ? ((int)Math.Round((double)totalCorrectAnswers / totalQuestionsAnswered * 100)).ToString() : "0";

                allTestAttempts = tps.Select(tp => new TestAttemptDto { TestTitle = tp.Test?.Title ?? "Тест", Difficulty = tp.Test?.Difficulty.ToString() ?? "", DifficultyText = tp.Test?.Difficulty switch { TestDifficulty.Easy => "Лёгкий", TestDifficulty.Medium => "Средний", TestDifficulty.Hard => "Сложный", _ => tp.Test?.Difficulty.ToString() ?? "" }, Status = tp.Status, StartedAt = tp.StartedAt, CompletedAt = tp.CompletedAt, TimeSpent = (tp.StartedAt.HasValue && tp.CompletedAt.HasValue) ? tp.CompletedAt.Value - tp.StartedAt.Value : null, CorrectAnswers = tp.Score, TotalQuestions = tp.Test?.Questions?.Count ?? 0 }).ToList();
                if (myTeamId.HasValue)
                {
                    var tu = await c.Set<UserTeam>().Where(t => t.Id == myTeamId.Value).SelectMany(t => t.Users).ToListAsync();
                    myTeamMembers.Clear();

                    foreach (var u in tu)
                    {
                        var uSoloScore = await c.UserProgresses.Where(p => p.UserId == u.Id && !p.IsTeamAttempt && p.Status == AttemptStatus.Completed).SumAsync(p => p.Score);
                        var uTeamScore = await c.UserProgresses.Where(p => p.TeamId == myTeamId.Value && p.IsTeamAttempt && p.Status == AttemptStatus.Completed).SumAsync(p => p.Score);
                        myTeamMembers.Add(new TeamMemberDto { Id = u.Id, Name = GetUserDisplayName(u), TotalScore = uSoloScore + uTeamScore });
                    }
                    myTeamMembers = myTeamMembers.OrderByDescending(m => m.TotalScore).ToList();
                }
            }
        }

        private async Task UpdateLeaderboards()
        {
            using var c = await ContextFactory.CreateDbContextAsync();
            int? gid = user?.GroupId; bool f = selectedFilter == "Мое подразделение" && gid.HasValue; var cuid = user?.Id;
            if (selectedCategory == "Сценарии")
            {
                var uq = c.Set<ApplicationUser>().Include(u => u.Group).AsQueryable();
                if (f) uq = uq.Where(u => u.GroupId == gid.Value);

                var topUsersQuery = await uq.Select(u => new
                {
                    u.Id,
                    LastName = u.LastName,
                    FirstName = u.FirstName,
                    MiddleName = u.MiddleName,
                    UserName = u.UserName,
                    GroupName = u.Group != null ? u.Group.Name : "",
                    Score = c.UserProgresses.Where(p => p.UserId == u.Id && p.Status == AttemptStatus.Completed && !p.IsTeamAttempt).Sum(p => (int?)p.Score) ?? 0,
                    CompletedCount = c.UserProgresses.Count(p => p.UserId == u.Id && p.Status == AttemptStatus.Completed && !p.IsTeamAttempt)
                })
                            .Where(x => x.Score > 0)
                            .OrderByDescending(x => x.Score)
                            .Take(15)
                            .ToListAsync();

                topUsers.Clear(); int ms = topUsersQuery.FirstOrDefault()?.Score ?? 0;
                for (int i = 0; i < topUsersQuery.Count; i++)
                {
                    var x = topUsersQuery[i];
                    var computedName = $"{x.LastName} {x.FirstName} {x.MiddleName}".Trim();
                    string dName = string.IsNullOrWhiteSpace(computedName) ? (x.UserName ?? "Оперативник") : computedName;

                    topUsers.Add(new UserLeaderboardDto
                    {
                        Rank = i + 1,
                        Name = dName,
                        GroupName = x.GroupName,
                        Score = x.Score,
                        CompletedCount = x.CompletedCount,
                        IsCurrentUser = x.Id == cuid,
                        Percentile = ms > 0 ? (int)Math.Round((double)x.Score / ms * 100) : 0
                    });
                }

                var tq = c.UserTeams.Include(t => t.Group).AsQueryable();
                if (f) tq = tq.Where(t => t.GroupId == gid.Value);
                var uti = user?.Teams?.Select(t => t.Id).ToList() ?? new List<int>();

                var topTeamsQuery = await tq.Select(t => new
                {
                    t.Id,
                    t.Name,
                    GroupName = t.Group != null ? t.Group.Name : "",
                    Score = c.UserProgresses.Where(p => p.TeamId == t.Id && p.Status == AttemptStatus.Completed && p.IsTeamAttempt).Sum(p => (int?)p.Score) ?? 0,
                    CompletedCount = c.UserProgresses.Count(p => p.TeamId == t.Id && p.Status == AttemptStatus.Completed && p.IsTeamAttempt)
                })
                            .Where(x => x.Score > 0)
                            .OrderByDescending(x => x.Score)
                            .Take(15)
                            .ToListAsync();

                topTeams.Clear(); ms = topTeamsQuery.FirstOrDefault()?.Score ?? 0;
                for (int i = 0; i < topTeamsQuery.Count; i++)
                {
                    var x = topTeamsQuery[i];
                    topTeams.Add(new TeamLeaderboardDto
                    {
                        Rank = i + 1,
                        Name = x.Name,
                        GroupName = x.GroupName,
                        Score = x.Score,
                        CompletedCount = x.CompletedCount,
                        IsUserTeam = uti.Contains(x.Id),
                        Percentile = ms > 0 ? (int)Math.Round((double)x.Score / ms * 100) : 0
                    });
                }
            }
            else
            {
                var uq = c.Set<ApplicationUser>().Include(u => u.Group).AsQueryable();
                if (f) uq = uq.Where(u => u.GroupId == gid.Value); var au = await uq.ToListAsync(); topTestUsers.Clear();
                foreach (var u in au)
                {
                    var tps = await c.Set<UserTestProgress>().Include(tp => tp.Test).ThenInclude(t => t.Questions).Where(tp => tp.UserId == u.Id && tp.Status == AttemptStatus.Completed).ToListAsync();
                    if (tps.Any())
                    {
                        double tpct = 0;
                        foreach (var tp in tps)
                        {
                            int tq = tp.Test?.Questions?.Count ?? 0;
                            if (tq > 0) tpct += (double)tp.Score / tq * 100;
                        }
                        topTestUsers.Add(new TestUserLeaderboardDto { Name = GetUserDisplayName(u), GroupName = u.Group?.Name ?? "", AverageScore = (int)Math.Round(tpct / tps.Count), CompletedCount = tps.Count, IsCurrentUser = u.Id == cuid });
                    }
                }
                topTestUsers = topTestUsers.OrderByDescending(u => u.AverageScore).ThenByDescending(u => u.CompletedCount).Take(15).ToList();
                for (int i = 0; i < topTestUsers.Count; i++) topTestUsers[i].Rank = i + 1;
                var allt = await c.Set<CyberTest>().Where(t => t.IsVisible).ToListAsync(); var act = await c.Set<UserTestProgress>().Include(tp => tp.Test).ThenInclude(t => t.Questions).Where(tp => tp.Status == AttemptStatus.Completed).ToListAsync();
                testLeaderboardStats = new TestLeaderboardStats
                {
                    TotalTests = allt.Count,
                    TotalCompleted = act.Count,
                    UniqueUsers = act.Select(tp => tp.UserId).Distinct().Count(),
                    OverallAverage = act.Any() ? (int)Math.Round(act.Average(tp => { int tq = tp.Test?.Questions?.Count ?? 0; return tq > 0 ? (double)tp.Score / tq * 100 : 0; })) : 0
                };
            }
        }

        public class TestAttemptDto { public string TestTitle { get; set; } = ""; public string Difficulty { get; set; } = ""; public string DifficultyText { get; set; } = ""; public AttemptStatus Status { get; set; } public DateTime? StartedAt { get; set; } public DateTime? CompletedAt { get; set; } public TimeSpan? TimeSpent { get; set; } public int CorrectAnswers { get; set; } public int TotalQuestions { get; set; } }
        public class TeamMemberDto { public string Id { get; set; } = ""; public string Name { get; set; } = ""; public int TotalScore { get; set; } }
        public class UserLeaderboardDto { public int Rank { get; set; } public string Name { get; set; } = ""; public string GroupName { get; set; } = ""; public int Score { get; set; } public int CompletedCount { get; set; } public int Percentile { get; set; } public bool IsCurrentUser { get; set; } }
        public class TeamLeaderboardDto { public int Rank { get; set; } public string Name { get; set; } = ""; public string GroupName { get; set; } = ""; public int Score { get; set; } public int CompletedCount { get; set; } public int Percentile { get; set; } public bool IsUserTeam { get; set; } }
        public class TestUserLeaderboardDto { public int Rank { get; set; } public string Name { get; set; } = ""; public string GroupName { get; set; } = ""; public int AverageScore { get; set; } public int CompletedCount { get; set; } public bool IsCurrentUser { get; set; } }
        public class TestLeaderboardStats { public int TotalTests { get; set; } public int TotalCompleted { get; set; } public int UniqueUsers { get; set; } public int OverallAverage { get; set; } }
    }
}
