// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.EntityFrameworkCore;
using Radzen;
using System.Security.Claims;

namespace CyberPolygon.Components.Pages
{
    public partial class Scenario
    {
        List<CyberScenario>? scenarios;
        private string currentUserId = string.Empty;
        private int? currentTeamId = null;
        private bool isAdmin = false;
        private readonly SemaphoreSlim _lock = new(1, 1);

        public class ProgressState
        {
            public AttemptStatus Status { get; set; } = AttemptStatus.NotStarted;
            public bool IsRetakeRequested { get; set; } = false;
            public bool IsRetakeGranted { get; set; } = false;
        }

        private Dictionary<int, ProgressState> userProgresses = new();

        protected override async Task OnInitializedAsync()
        {
            CatalogUpdateService.OnCatalogChanged += HandleExternalUpdate;
            SessionManager.TeamProgressChanged += OnTeamProgressChanged;

            await Refresh();
        }

        private async void HandleExternalUpdate()
        {
            await InvokeAsync(async () =>
            {
                await Refresh();
                StateHasChanged();
            });
        }

        private async void OnTeamProgressChanged(int teamId)
        {
            if (currentTeamId == teamId)
            {
                await InvokeAsync(async () =>
                {
                    await Refresh();
                    StateHasChanged();
                });
            }
        }

        async Task Refresh()
        {
            if (!await _lock.WaitAsync(0)) return;

            try
            {
                var allScenarios = await ScenarioService.GetAllAsync();
                var authState = await AuthStateProvider.GetAuthenticationStateAsync();
                var userPrincipal = authState.User;
                currentUserId = userPrincipal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
                isAdmin = userPrincipal.IsInRole("Admin") || userPrincipal.IsInRole("SuperAdmin");

                userProgresses.Clear();

                if (!string.IsNullOrEmpty(currentUserId))
                {
                    using var context = await ContextFactory.CreateDbContextAsync();
                    var dbUser = await context.Set<ApplicationUser>().Include(u => u.Teams).AsNoTracking().FirstOrDefaultAsync(u => u.Id == currentUserId);
                    currentTeamId = dbUser?.Teams?.FirstOrDefault()?.Id;

                    var progresses = await context.Set<UserScenarioProgress>()
                        .Where(p => p.UserId == currentUserId || (currentTeamId.HasValue && p.TeamId == currentTeamId.Value))
                        .OrderByDescending(p => p.Id) // <-- МАГИЯ ЗДЕСЬ: берем самую свежую запись
                        .AsNoTracking()
                        .ToListAsync();

                    foreach (var item in allScenarios)
                    {
                        UserScenarioProgress? p = null;
                        if (item.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue)
                            p = progresses.FirstOrDefault(x => x.CyberScenarioId == item.Id && x.TeamId == currentTeamId.Value && x.IsTeamAttempt);
                        else
                            p = progresses.FirstOrDefault(x => x.CyberScenarioId == item.Id && x.UserId == currentUserId && !x.IsTeamAttempt);

                        if (p != null)
                        {
                            userProgresses[item.Id] = new ProgressState
                            {
                                Status = p.Status,
                                IsRetakeRequested = p.IsRetakeRequested,
                                IsRetakeGranted = p.IsRetakeGranted
                            };
                        }
                    }
                }

                if (isAdmin)
                {
                    scenarios = allScenarios;
                }
                else
                {
                    using var context = await ContextFactory.CreateDbContextAsync();
                    var dbUser = await context.Set<ApplicationUser>().Include(u => u.Teams).AsNoTracking().FirstOrDefaultAsync(u => u.Id == currentUserId);
                    if (dbUser == null) { scenarios = new List<CyberScenario>(); return; }

                    var userTeamIds = dbUser.Teams?.Select(t => t.Id).ToList() ?? new List<int>();
                    scenarios = allScenarios.Where(s => s.IsVisible && (s.Scope == VisibilityScope.Public || (s.Scope == VisibilityScope.GroupOnly && !string.IsNullOrEmpty(s.AllowedUserIds) && s.AllowedUserIds.Contains(currentUserId)) || (s.Scope == VisibilityScope.TeamOnly && !string.IsNullOrEmpty(s.AllowedTeamIds) && userTeamIds.Any(t => s.AllowedTeamIds.Contains(t.ToString()))))).ToList();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Ошибка загрузки: {ex.Message}");
                scenarios ??= new List<CyberScenario>();
            }
            finally
            {
                _lock.Release();
            }
        }

        void OpenEditDialog(CyberScenario scenario) => NavigationManager.NavigateTo($"/scenario/edit/{scenario.Id}");

        bool isDeleteVisualDialogVisible = false; int scenarioIdToDelete = 0;
        void DeleteItem(int id) { scenarioIdToDelete = id; isDeleteVisualDialogVisible = true; }

        async Task ConfirmDelete()
        {
            isDeleteVisualDialogVisible = false;
            if (scenarioIdToDelete != 0)
            {
                await ScenarioService.DeleteAsync(scenarioIdToDelete);
                CatalogUpdateService.NotifyCatalogChanged();
                NotificationService.Notify(NotificationSeverity.Success, "Система", "Данные удалены");
            }
            scenarioIdToDelete = 0;
        }

        void CloseDeleteDialog() { isDeleteVisualDialogVisible = false; scenarioIdToDelete = 0; }

        private int GetDifficultyOrder(string difficulty) => difficulty switch { "Легкий" => 1, "Средний" => 2, "Сложный" => 3, _ => 4 };
        private string GetDifficultyClass(string difficulty) => difficulty switch { "Легкий" => "diff-easy", "Средний" => "diff-medium", "Сложный" => "diff-hard", _ => "diff-easy" };
        private string GetDifficultyColor(string difficulty) => difficulty switch { "Легкий" => "var(--success-color)", "Средний" => "var(--warning-color)", "Сложный" => "var(--danger-color)", _ => "var(--text-light)" };

        public void Dispose()
        {
            CatalogUpdateService.OnCatalogChanged -= HandleExternalUpdate;
            SessionManager.TeamProgressChanged -= OnTeamProgressChanged;
        }
        public class StatRecord
        {
            public string Name { get; set; } = string.Empty;
            public int AttemptNumber { get; set; }
            public string StatusText { get; set; } = string.Empty;
            public int Score { get; set; }
        }

        private bool isStatsDialogVisible = false;
        private List<StatRecord> scenarioStats = new();

        private async Task OpenScenarioStats(int scenarioId)
        {
            scenarioStats.Clear();
            using var context = await ContextFactory.CreateDbContextAsync();

            // Достаем все попытки, отсортированные по времени старта (от старых к новым)
            var progresses = await context.Set<UserScenarioProgress>()
                .Include(p => p.Team)
                .Where(p => p.CyberScenarioId == scenarioId)
                .OrderBy(p => p.StartedAt)
                .ToListAsync();

            var userIds = progresses.Where(p => p.UserId != null).Select(p => p.UserId).Distinct().ToList();
            var users = await context.Users.Where(u => userIds.Contains(u.Id)).ToDictionaryAsync(u => u.Id, u => u.UserName ?? "Неизвестно");

            var userAttemptCounts = new Dictionary<string, int>();
            var teamAttemptCounts = new Dictionary<int, int>();

            foreach (var p in progresses)
            {
                string name = "Неизвестно";
                int attempt = 1;

                if (p.IsTeamAttempt && p.TeamId.HasValue)
                {
                    name = p.Team?.Name ?? "Удаленная команда";
                    if (!teamAttemptCounts.ContainsKey(p.TeamId.Value)) teamAttemptCounts[p.TeamId.Value] = 0;
                    teamAttemptCounts[p.TeamId.Value]++;
                    attempt = teamAttemptCounts[p.TeamId.Value];
                    name = "[Команда] " + name;
                }
                else if (p.UserId != null)
                {
                    name = users.ContainsKey(p.UserId) ? users[p.UserId] : "Удаленный пользователь";
                    if (!userAttemptCounts.ContainsKey(p.UserId)) userAttemptCounts[p.UserId] = 0;
                    userAttemptCounts[p.UserId]++;
                    attempt = userAttemptCounts[p.UserId];
                }

                string statusText = p.Status switch
                {
                    AttemptStatus.Completed => "Выполнено",
                    AttemptStatus.Failed => "Провалено",
                    AttemptStatus.InProgress => "В процессе",
                    _ => "Не начато"
                };

                scenarioStats.Add(new StatRecord
                {
                    Name = name,
                    AttemptNumber = attempt,
                    StatusText = statusText,
                    Score = p.Score
                });
            }

            // Переворачиваем список, чтобы самые свежие попытки были сверху
            scenarioStats.Reverse();
            isStatsDialogVisible = true;
        }

        private void CloseStatsDialog() => isStatsDialogVisible = false;
    }
}