// <auto-generated/>
using CyberPolygon.Data;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.JSInterop;
using Radzen;
using System.Security.Claims;

namespace CyberPolygon.Components.Pages
{
    public partial class ScenarioWorkspace
    {
        [Parameter] public int Id { get; set; }
        private CyberScenario? scenario;
        private UserScenarioProgress? currentUserProgress;
        private string currentUserId = string.Empty;
        private int? currentTeamId = null;

        private Timer? _timer;
        private TimeSpan timeLeft = TimeSpan.Zero;
        private int totalScore = 0;
        private bool isMapInitialized = false;
        private bool _isDisposed = false;

        private int canvasWidth = 800;
        private int canvasHeight = 550;

        public class UserQuestionState
        {
            public ScenarioQuestion Question { get; set; } = new();
            public string UserAnswer { get; set; } = string.Empty;
            public bool IsCorrect { get; set; } = false;
            public string FeedbackMessage { get; set; } = string.Empty;
            public int FailedAttempts { get; set; } = 0;
            public int CurrentAward => Question.PenaltyPoints <= 0 ? Question.AwardPoints : Math.Max(0, Question.AwardPoints - (FailedAttempts * Question.PenaltyPoints));
        }

        private List<UserQuestionState> questionStates = new();

        private async Task FocusOnDevice(int x, int y)
        {
            try { await JSRuntime.InvokeVoidAsync("imageViewer.focusOnCoordinates", "schema-drag-container", x, y); } catch { }
        }

        protected override async Task OnInitializedAsync()
        {
            try
            {
                scenario = await ScenarioService.GetByIdAsync(Id);
                if (scenario == null) { NavigationManager.NavigateTo("/scenario"); return; }

                if (scenario.Questions != null)
                {
                    questionStates = scenario.Questions.Select(q => new UserQuestionState { Question = q }).ToList();
                }

                var authState = await AuthStateProvider.GetAuthenticationStateAsync();
                var user = authState.User;
                if (user.Identity?.IsAuthenticated == true)
                {
                    currentUserId = user.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
                    using var ctx = await ContextFactory.CreateDbContextAsync();
                    var dbUser = await ctx.Set<ApplicationUser>().Include(u => u.Teams).AsNoTracking().FirstOrDefaultAsync(u => u.Id == currentUserId);
                    currentTeamId = dbUser?.Teams?.FirstOrDefault()?.Id;

                    await LoadUserState();
                }
                SessionManager.TeamProgressChanged += OnTeamProgressChanged;
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Критический сбой инициализации", ex.Message);
            }
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender && !isMapInitialized && currentUserProgress?.Status == AttemptStatus.InProgress)
            {
                isMapInitialized = true;
                try { await JSRuntime.InvokeVoidAsync("imageViewer.init", "schema-drag-container", "topology-move-layer"); } catch { }
            }
        }

        private async Task LoadUserState()
        {
            if (scenario == null) return;

            try
            {
                using var context = await ContextFactory.CreateDbContextAsync();

                if (scenario.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue)
                {
                    currentUserProgress = await context.UserProgresses
                        .FirstOrDefaultAsync(p => p.CyberScenarioId == Id && p.TeamId == currentTeamId && p.Status == AttemptStatus.InProgress);
                }
                else
                {
                    currentUserProgress = await context.UserProgresses
                        .FirstOrDefaultAsync(p => p.CyberScenarioId == Id && p.UserId == currentUserId && p.Status == AttemptStatus.InProgress);
                }

                if (currentUserProgress == null)
                {
                    if (scenario.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue)
                    {
                        currentUserProgress = await context.UserProgresses
                            .OrderByDescending(p => p.StartedAt)
                            .FirstOrDefaultAsync(p => p.CyberScenarioId == Id && p.TeamId == currentTeamId);
                    }
                    else
                    {
                        currentUserProgress = await context.UserProgresses
                            .OrderByDescending(p => p.StartedAt)
                            .FirstOrDefaultAsync(p => p.CyberScenarioId == Id && p.UserId == currentUserId);
                    }
                }

                if (currentUserProgress == null)
                {
                    currentUserProgress = new UserScenarioProgress
                    {
                        Status = AttemptStatus.NotStarted,
                        CyberScenarioId = Id
                    };
                }

                totalScore = currentUserProgress.Score;

                if (scenario.Questions != null && currentUserProgress.Id != 0)
                {
                    var solvedAnswers = await context.UserAnswerProgresses
                        .Where(a => a.UserScenarioProgressId == currentUserProgress.Id)
                        .ToListAsync();

                    questionStates = scenario.Questions.Select(q =>
                    {
                        var solved = solvedAnswers.FirstOrDefault(a => a.QuestionId == q.Id);
                        return new UserQuestionState
                        {
                            Question = q,
                            IsCorrect = solved?.IsCorrect ?? false,
                            FailedAttempts = solved?.FailedAttempts ?? 0,
                            UserAnswer = solved?.LastSubmittedAnswer ?? string.Empty
                        };
                    }).ToList();
                }

                var freshDevices = await context.Set<ScenarioDevice>()
                    .Include(d => d.Applications)
                    .Where(d => d.CyberScenarioId == scenario.Id)
                    .ToListAsync();

                if (freshDevices != null)
                {
                    scenario.Devices = freshDevices;
                    CalculateCanvasBounds();
                }

                if (currentUserProgress.Status == AttemptStatus.InProgress)
                {
                    StartTimer();
                }
                else
                {
                    StopTimer();
                }
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка базы данных", ex.Message);
            }
        }

        private void CalculateCanvasBounds()
        {
            if (scenario?.Devices != null && scenario.Devices.Any())
            {
                int maxX = scenario.Devices.Max(d => d.MapX);
                int maxY = scenario.Devices.Max(d => d.MapY);

                canvasWidth = Math.Max(800, maxX + 150);
                canvasHeight = Math.Max(550, maxY + 150);
            }
            else
            {
                canvasWidth = 800;
                canvasHeight = 550;
            }
        }

        private async void OnTeamProgressChanged(int teamId)
        {
            if (_isDisposed) return;
            if (scenario?.Scope == VisibilityScope.TeamOnly && currentTeamId == teamId)
            {
                await InvokeAsync(async () => { await LoadUserState(); StateHasChanged(); });
            }
        }

        private async Task StartScenario()
        {
            if (scenario == null || string.IsNullOrEmpty(currentUserId)) return;

            var (success, msg) = await SessionManager.CheckConcurrencyAsync(currentUserId, currentTeamId);
            if (!success)
            {
                NotificationService.Notify(NotificationSeverity.Warning, "Предупреждение", msg);
                return;
            }

            try
            {
                using var context = await ContextFactory.CreateDbContextAsync();

                var newProgress = new UserScenarioProgress
                {
                    UserId = scenario.Scope == VisibilityScope.TeamOnly ? null : currentUserId,
                    TeamId = currentTeamId,
                    IsTeamAttempt = scenario.Scope == VisibilityScope.TeamOnly,
                    CyberScenarioId = scenario.Id,
                    Score = 0,
                    Status = AttemptStatus.InProgress,
                    StartedAt = DateTime.UtcNow,
                    TargetEndTime = scenario.DurationInMinutes > 0 ? DateTime.UtcNow.AddMinutes(scenario.DurationInMinutes) : null
                };

                context.UserProgresses.Add(newProgress);
                await context.SaveChangesAsync();

                await LoadUserState();

                if (scenario.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue)
                    SessionManager.NotifyTeamUpdate(currentTeamId.Value);

                NotificationService.Notify(NotificationSeverity.Success, "Система", "Симуляция инфраструктуры успешно запущена!");

                await InvokeAsync(StateHasChanged);
                await Task.Delay(100);

                if (!isMapInitialized)
                {
                    isMapInitialized = true;
                    try { await JSRuntime.InvokeVoidAsync("imageViewer.init", "schema-drag-container", "topology-move-layer"); } catch { }
                }
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Критическая ошибка старта", ex.Message);
            }
        }

        private async Task CheckAnswer(UserQuestionState state)
        {
            if (string.IsNullOrWhiteSpace(state.UserAnswer) || currentUserProgress?.Status != AttemptStatus.InProgress) return;
            try
            {
                var result = await ScenarioService.ProcessTeamAnswerAsync(currentUserProgress.Id, state.Question.Id, state.UserAnswer, currentUserId, currentTeamId);
                if (!result.Success)
                {
                    if (result.AlreadySolved) state.IsCorrect = true;
                    else { state.FailedAttempts++; state.FeedbackMessage = "❌ Неверный флаг."; }
                    if (scenario!.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue) SessionManager.NotifyTeamUpdate(currentTeamId.Value);
                    StateHasChanged(); return;
                }

                totalScore = result.NewTotalScore;
                state.IsCorrect = true;
                state.FeedbackMessage = "✅ Флаг принят!";

                if (scenario!.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue) SessionManager.NotifyTeamUpdate(currentTeamId.Value);
                StateHasChanged();

                if (questionStates.All(q => q.IsCorrect)) await CompleteScenario();
            }
            catch (Exception ex)
            {
                NotificationService.Notify(NotificationSeverity.Error, "Ошибка проверки флага", ex.Message);
            }
        }

        private async Task HandleKeyPress(KeyboardEventArgs e, UserQuestionState state)
        {
            if (e.Key == "Enter") await CheckAnswer(state);
        }

        private async Task CompleteScenario()
        {
            var result = await DialogService.Confirm(
               "Вы действительно хотите досрочно завершить тестирование?",
               "Завершение попытки",
               new ConfirmOptions() { OkButtonText = "Да, завершить", CancelButtonText = "Продолжить тест" });

            if (result == true)
            {
                StopTimer();
                if (currentUserProgress != null && currentUserProgress.Id != 0)
                {
                    try
                    {
                        using var context = await ContextFactory.CreateDbContextAsync();
                        var p = await context.Set<UserScenarioProgress>().FindAsync(currentUserProgress.Id);
                        if (p != null)
                        {
                            p.Status = AttemptStatus.Completed;
                            p.CompletedAt = DateTime.UtcNow;
                            context.Set<UserScenarioProgress>().Update(p);
                            await context.SaveChangesAsync();
                        }
                        await LoadUserState();
                        if (scenario!.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue) SessionManager.NotifyTeamUpdate(currentTeamId.Value);
                        StateHasChanged();
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                }
            }
            
        }

        private async void TimerTick(object? state)
        {
            if (_isDisposed) return;

            if (currentUserProgress?.TargetEndTime != null)
            {
                timeLeft = currentUserProgress.TargetEndTime.Value - DateTime.UtcNow;

                if (timeLeft.TotalSeconds <= 0)
                {
                    StopTimer();
                    await InvokeAsync(ForceFailScenario);
                }
                else
                {
                    await InvokeAsync(StateHasChanged);
                }
            }
        }

        private void StartTimer()
        {
            if (scenario != null && scenario.DurationInMinutes > 0 && currentUserProgress?.TargetEndTime != null)
            {
                _timer?.Dispose();
                _timer = new Timer(TimerTick, null, 0, 1000);
            }
        }

        private void StopTimer() => _timer?.Dispose();

        private async Task ForceFailScenario()
        {
            if (currentUserProgress != null && currentUserProgress.Id != 0)
            {
                try
                {
                    using var context = await ContextFactory.CreateDbContextAsync();
                    var progress = await context.Set<UserScenarioProgress>().FindAsync(currentUserProgress.Id);
                    if (progress != null && progress.Status == AttemptStatus.InProgress)
                    {
                        progress.Status = AttemptStatus.Failed;
                        progress.CompletedAt = DateTime.UtcNow;

                        if (progress.StartedAt.HasValue)
                            progress.TimeSpent = progress.CompletedAt.Value - progress.StartedAt.Value;

                        context.Set<UserScenarioProgress>().Update(progress);
                        await context.SaveChangesAsync();
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            await InvokeAsync(async () => { await LoadUserState(); StateHasChanged(); });

            if (scenario!.Scope == VisibilityScope.TeamOnly && currentTeamId.HasValue)
                SessionManager.NotifyTeamUpdate(currentTeamId.Value);
        }

        private async Task RequestRetake()
        {
            if (currentUserProgress != null)
            {
                await ScenarioService.RequestRetakeAsync(currentUserProgress.Id);
                await LoadUserState();
                NotificationService.Notify(NotificationSeverity.Success, "Запрос отправлен", "Ожидайте решения администратора.");
            }
        }

        public void Dispose()
        {
            _isDisposed = true;
            StopTimer();
            SessionManager.TeamProgressChanged -= OnTeamProgressChanged;
        }
    }
}