// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Radzen;
using System.Security.Claims;

namespace CyberPolygon.Components.Pages
{
    public partial class TestWorkspace
    {
        [Parameter] public int Id { get; set; }

        private CyberTest? test;
        private UserTestProgress? progress;
        private List<QuestionUIState>? activeStates;
        private string currentUserId = string.Empty;
        private bool isTestStarted = false;
        private bool isTestFinished = false;
        private int correctCount = 0;

        private System.Threading.Timer? _timer;
        private TimeSpan timeLeft;

        public class QuestionUIState
        {
            public TestQuestion Question { get; set; } = null!;
            public bool IsAnswered { get; set; }
            public bool IsCorrect { get; set; }
            public string UserTextAnswer { get; set; } = string.Empty;
            public int SelectedOptionId { get; set; }
            public Dictionary<int, bool> SelectedMultipleOptions { get; set; } = new();
        }
        // Функция для вычисления процента успешности
        private double CalculatePercentage()
        {
            if (test == null || test.Questions.Count == 0) return 0;
            return Math.Round((double)correctCount / test.Questions.Count * 100, 1);
        }

        protected override async Task OnInitializedAsync()
        {
            var authState = await AuthStateProvider.GetAuthenticationStateAsync();
            currentUserId = authState.User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;

            test = await TestService.GetByIdAsync(Id);
            if (test == null) { NavigationManager.NavigateTo("/tests"); return; }

            await LoadProgress();
        }

        private async Task LoadProgress()
        {
            progress = await TestService.GetUserProgressAsync(currentUserId, Id);
            activeStates = test!.Questions.Select(q =>
            {
                var state = new QuestionUIState { Question = q };
                if (q.Type == QuestionType.MultipleChoice)
                    foreach (var opt in q.Options)
                        state.SelectedMultipleOptions[opt.Id] = false;
                return state;
            }).ToList();

            isTestStarted = false;
            isTestFinished = false;
            correctCount = 0;
            _timer?.Dispose();

            if (progress != null && progress.Status != AttemptStatus.NotStarted)
            {
                isTestStarted = true;
                correctCount = progress.Score;

                var correctIds = await TestService.GetAnsweredCorrectlyAsync(progress.Id);
                var wrongIds = await TestService.GetAnsweredWrongAsync(progress.Id);

                foreach (var state in activeStates)
                {
                    if (correctIds.Contains(state.Question.Id)) { state.IsAnswered = true; state.IsCorrect = true; }
                    if (wrongIds.Contains(state.Question.Id)) { state.IsAnswered = true; state.IsCorrect = false; }
                }

                if (progress.Status == AttemptStatus.Completed)
                    isTestFinished = true;
                else if (progress.TargetEndTime.HasValue)
                    StartTimer();
            }
        }

        private async Task StartTest()
        {
            await TestService.StartTestAsync(currentUserId, Id, test!.DurationInMinutes);
            await LoadProgress();
            if (progress?.TargetEndTime.HasValue == true)
                StartTimer();
        }

        // ВОССТАНОВЛЕННЫЙ МЕТОД ДЛЯ ПОВТОРНОГО ЗАПУСКА
        private async Task RestartTest()
        {
            await TestService.RestartTestAsync(currentUserId, Id);
            // Сразу начинаем новую попытку
            await TestService.StartTestAsync(currentUserId, Id, test!.DurationInMinutes);
            await LoadProgress();
            if (progress?.TargetEndTime.HasValue == true)
                StartTimer();
        }

        // МЕТОД ЗАПРОСА НА ПЕРЕСДАЧУ
        private async Task RequestRetake()
        {
            if (progress != null)
            {
                await TestService.RequestRetakeAsync(progress.Id);
                await LoadProgress();
                NotificationService.Notify(NotificationSeverity.Success, "Запрос отправлен", "Ожидайте решения администратора.");
            }
        }

        private async Task ConfirmAnswer(QuestionUIState state)
        {
            var result = await DialogService.Confirm(
                "Вы уверены? Изменить ответ в рамках этой попытки будет невозможно.",
                "Подтверждение ответа",
                new ConfirmOptions() { OkButtonText = "Да, подтверждаю", CancelButtonText = "Отмена" });

            if (result == true)
            {
                bool isRight = false;
                string? selectedAnswer = null;

                if (state.Question.Type == QuestionType.ManualText)
                {
                    var correctAnswer = state.Question.CorrectTextAnswer?.Trim() ?? "";
                    isRight = string.Equals(state.UserTextAnswer.Trim(), correctAnswer, StringComparison.OrdinalIgnoreCase);
                    selectedAnswer = state.UserTextAnswer;
                }
                else if (state.Question.Type == QuestionType.SingleChoice)
                {
                    var correctOpt = state.Question.Options.FirstOrDefault(o => o.IsCorrect == true);
                    isRight = correctOpt != null && correctOpt.Id == state.SelectedOptionId;
                    selectedAnswer = state.SelectedOptionId.ToString();
                }
                else if (state.Question.Type == QuestionType.MultipleChoice)
                {
                    var correctIds = state.Question.Options.Where(o => o.IsCorrect == true).Select(o => o.Id).OrderBy(x => x).ToList();
                    var userSelectedIds = state.SelectedMultipleOptions.Where(kvp => kvp.Value).Select(kvp => kvp.Key).OrderBy(x => x).ToList();
                    isRight = correctIds.SequenceEqual(userSelectedIds);
                    selectedAnswer = string.Join(",", userSelectedIds);
                }

                await TestService.ProcessAnswerAsync(progress!.Id, state.Question.Id, isRight, selectedAnswer ?? "");
                state.IsAnswered = true;
                state.IsCorrect = isRight;
                if (isRight) correctCount++;

                if (activeStates!.All(s => s.IsAnswered))
                {
                    await TestService.CompleteTestAsync(progress.Id);
                    isTestFinished = true;
                    _timer?.Dispose();
                    NotificationService.Notify(NotificationSeverity.Success, "Тест завершен", "Все вопросы отвечены!");
                }
            }
        }

        private async Task FinishTestDialog()
        {
            var result = await DialogService.Confirm(
                "Вы действительно хотите досрочно завершить тестирование?",
                "Завершение попытки",
                new ConfirmOptions() { OkButtonText = "Да, завершить", CancelButtonText = "Продолжить тест" });

            if (result == true)
            {
                _timer?.Dispose();
                await TestService.CompleteTestAsync(progress!.Id);
                isTestFinished = true;
            }
        }

        private void StartTimer()
        {
            _timer?.Dispose();
            _timer = new System.Threading.Timer(async _ => await InvokeAsync(TimerTick), null, 0, 1000);
        }

        private async Task TimerTick()
        {
            if (progress?.TargetEndTime != null)
            {
                timeLeft = progress.TargetEndTime.Value - DateTime.UtcNow;

                if (timeLeft.TotalSeconds <= 0)
                {
                    _timer?.Dispose();
                    await TestService.CompleteTestAsync(progress.Id);
                    isTestFinished = true;
                    NotificationService.Notify(NotificationSeverity.Error, "Время вышло", "Тестирование было автоматически завершено системой.");
                }

                await InvokeAsync(StateHasChanged);
            }
        }
    }
}