// <auto-generated/>
using Microsoft.EntityFrameworkCore;
using Radzen;

namespace CyberPolygon.Components.Pages
{
    public partial class Tests
    {
        List<CyberTest>? tests;
        private string currentUserId = string.Empty;
        private bool isAdmin = false;
        private readonly SemaphoreSlim _lock = new(1, 1);

        // ОБНОВЛЕНО: Используем класс для хранения статуса и флагов ретейка
        public class ProgressState
        {
            public AttemptStatus Status { get; set; } = AttemptStatus.NotStarted;
            public bool IsRetakeRequested { get; set; } = false;
            public bool IsRetakeGranted { get; set; } = false;
        }

        private Dictionary<int, ProgressState> userProgresses = new();

        protected override async Task OnInitializedAsync()
        {
            CatalogUpdateService.OnCatalogChanged += HandleCatalogChanged;
            await Refresh();
        }

        private async void HandleCatalogChanged()
        {
            await InvokeAsync(async () =>
            {
                await Refresh();
                StateHasChanged();
            });
        }

        async Task Refresh()
        {
            if (!await _lock.WaitAsync(0)) return;

            try
            {
                var allTests = await TestService.GetAllAsync();
                var authState = await AuthStateProvider.GetAuthenticationStateAsync();
                var userPrincipal = authState.User;
                currentUserId = userPrincipal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
                isAdmin = userPrincipal.IsInRole("Admin") || userPrincipal.IsInRole("SuperAdmin");

                userProgresses.Clear();

                if (!string.IsNullOrEmpty(currentUserId))
                {
                    using var context = await ContextFactory.CreateDbContextAsync();
                    var progresses = await context.Set<UserTestProgress>()
                        .Where(p => p.UserId == currentUserId)
                        .AsNoTracking()
                        .ToListAsync();

                    foreach (var p in progresses)
                    {
                        if (p.Status == AttemptStatus.InProgress && p.TargetEndTime.HasValue && DateTime.UtcNow >= p.TargetEndTime.Value)
                        {
                            p.Status = AttemptStatus.Failed; p.CompletedAt = DateTime.UtcNow;
                            context.Set<UserTestProgress>().Update(p); await context.SaveChangesAsync();
                        }
                        if (!userProgresses.ContainsKey(p.CyberTestId) || p.Status == AttemptStatus.InProgress)
                        {
                            userProgresses[p.CyberTestId] = new ProgressState
                            {
                                Status = p.Status,
                                IsRetakeRequested = p.IsRetakeRequested,
                                IsRetakeGranted = p.IsRetakeGranted
                            };
                        }
                    }
                }

                if (isAdmin)
                {
                    tests = allTests;
                }
                else
                {
                    tests = allTests.Where(t => t.IsVisible && (
                        t.Scope == VisibilityScope.Public ||
                        (t.Scope == VisibilityScope.GroupOnly && !string.IsNullOrEmpty(t.AllowedUserIds) && t.AllowedUserIds.Contains(currentUserId))
                    )).ToList();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Ошибка загрузки каталога тестов: {ex.Message}");
                tests ??= new List<CyberTest>();
            }
            finally
            {
                _lock.Release();
            }
        }

        bool isDeleteVisualDialogVisible = false; int testIdToDelete = 0;
        void DeleteItem(int id) { testIdToDelete = id; isDeleteVisualDialogVisible = true; }

        async Task ConfirmDelete()
        {
            isDeleteVisualDialogVisible = false;
            if (testIdToDelete != 0)
            {
                await TestService.DeleteAsync(testIdToDelete);

                // СИГНАЛ: Сообщаем всем, что тест удален!
                CatalogUpdateService.NotifyCatalogChanged();

                NotificationService.Notify(NotificationSeverity.Success, "Система", "Тест успешно удален.");
            }
            testIdToDelete = 0;
        }
        void CloseDeleteDialog() { isDeleteVisualDialogVisible = false; testIdToDelete = 0; }

        private string GetDifficultyClass(TestDifficulty diff) => diff switch { TestDifficulty.Easy => "diff-easy", TestDifficulty.Medium => "diff-medium", _ => "diff-hard" };
        private string GetDifficultyText(TestDifficulty diff) => diff switch { TestDifficulty.Easy => "Легкий", TestDifficulty.Medium => "Средний", _ => "Сложный" };
        private string GetDifficultyColor(TestDifficulty diff) => diff switch { TestDifficulty.Easy => "var(--success-color)", TestDifficulty.Medium => "var(--warning-color)", _ => "var(--danger-color)" };

        public void Dispose()
        {
            CatalogUpdateService.OnCatalogChanged -= HandleCatalogChanged;
        }
        public class TestStatRecord
        {
            public int ProgressId { get; set; }
            public string Name { get; set; } = string.Empty;
            public int AttemptNumber { get; set; }
            public string StatusText { get; set; } = string.Empty;
            public double Percentage { get; set; }
        }

        private bool isStatsDialogVisible = false;
        private List<TestStatRecord> testStats = new();

        private async Task OpenTestStats(int testId)
        {
            testStats.Clear();
            using var context = await ContextFactory.CreateDbContextAsync();

            // Вытягиваем тест вместе с вопросами, чтобы узнать их общее количество
            var test = await context.CyberTests.Include(t => t.Questions).FirstOrDefaultAsync(t => t.Id == testId);
            int totalQuestions = test?.Questions?.Count ?? 0;

            var progresses = await context.Set<UserTestProgress>()
                .Where(p => p.CyberTestId == testId)
                .OrderBy(p => p.StartedAt) // Хронологический порядок
                .ToListAsync();

            var userIds = progresses.Where(p => p.UserId != null).Select(p => p.UserId).Distinct().ToList();
            // Вытягиваем данные профиля (ФИО и логин)
            var usersData = await context.Users
                .Where(u => userIds.Contains(u.Id))
                .Select(u => new { u.Id, u.UserName, u.FirstName, u.LastName, u.MiddleName })
                .ToListAsync();

            // Формируем словарь: если ФИО не пустое - берем его, иначе берем логин
            var users = usersData.ToDictionary(
                u => u.Id,
                u =>
                {
                    string fullName = $"{u.LastName} {u.FirstName} {u.MiddleName}".Trim();
                    return string.IsNullOrWhiteSpace(fullName) ? (u.UserName ?? "Неизвестно") : fullName;
                });

            var userAttemptCounts = new Dictionary<string, int>();

            foreach (var p in progresses)
            {
                string name = "Удаленный пользователь";
                int attempt = 1;

                if (p.UserId != null)
                {
                    name = users.ContainsKey(p.UserId) ? users[p.UserId] : "Удаленный пользователь";
                    if (!userAttemptCounts.ContainsKey(p.UserId)) userAttemptCounts[p.UserId] = 0;
                    userAttemptCounts[p.UserId]++;
                    attempt = userAttemptCounts[p.UserId];
                }

                string statusText = p.Status switch
                {
                    AttemptStatus.Completed => "Выполнено",
                    AttemptStatus.Failed => "Провалено",
                    AttemptStatus.InProgress => "В процессе",
                    _ => "Не начато"
                };

                // Вычисляем процент прямо здесь для вывода администратору
                double pct = totalQuestions > 0 ? Math.Round((double)p.Score / totalQuestions * 100, 1) : 0;

                testStats.Add(new TestStatRecord
                {
                    ProgressId = p.Id,
                    Name = name,
                    AttemptNumber = attempt,
                    StatusText = statusText,
                    Percentage = pct
                });
            }

            testStats.Reverse();
            isStatsDialogVisible = true;
        }

        private void CloseStatsDialog() => isStatsDialogVisible = false;
    }

}